### ISSUE TITLE
Unable to invite player to party

### ISSUE THREAD

**Issue by farsdewibs0n** [Nibato/nibmods-7dtd#1]
When I try to invite player to my party, this error shown and doesn't send party invitation
![image](https://user-images.githubusercontent.com/13050356/165362275-38460962-3fa2-4fca-bdec-4e092db7eaa8.png)

**Comment by Nibato** [comment]
What version/build of 7 days are you playing on?

**Comment by Cronosus** [comment]
same errors, with two latest builds
A20.3 - sometimes not works
A20.4 (b42) - not works and error

**Comment by Nibato** [comment]
I've finally had some time to look at this, and I believe it just needed to be recompiled for the latest version.

I've attached those versions below. Please let me know if this solves the issue and I'll make it an official release.

[AutoAcceptPartyInvite_v1.0.1_A20.4.zip](https://github.com/Nibato/nibmods-7dtd/files/8653366/AutoAcceptPartyInvite_v1.0.1_A20.4.zip)
[AutoQuestShare_v1.0.1_A20.4.zip](https://github.com/Nibato/nibmods-7dtd/files/8653367/AutoQuestShare_v1.0.1_A20.4.zip)
[FocalLengthAiming_v1.0.2_A20.4.zip](https://github.com/Nibato/nibmods-7dtd/files/8653368/FocalLengthAiming_v1.0.2_A20.4.zip)
[ProperMagnification_v1.0.2_A20.4.zip](https://github.com/Nibato/nibmods-7dtd/files/8653369/ProperMagnification_v1.0.2_A20.4.zip)
[UnlockedByDefault_v1.0.1_A20.4.zip](https://github.com/Nibato/nibmods-7dtd/files/8653370/UnlockedByDefault_v1.0.1_A20.4.zip)

**Comment by Cronosus** [comment]
thanks, ill try on weekend (only then i can play, cause of work)

**Comment by Cronosus** [comment]
looks like its still not working, but atleast its not givin any error, so i can accept/invite manually

**Comment by Nibato** [comment]
Due to how fragile this mod seems to be between updates, I'm probably not going to personally continue work on anything other than FocalLengthAiming and ProperMagnification for the foreseeable future.
